name: 'Publish extension'
description: 'Publish extension to Open VSX Marketplace'

inputs:
  open_vsx_token:
    description: 'Open VSX token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Publish to Open VSX
      shell: bash
      run: npx ovsx publish -p ${{ inputs.open_vsx_token }}
